name: "Release Package Version"
on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        required: true
        description: Select a version type for release
        options:
          - major
          - minor
          - patch
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: "${{ github.event.inputs.releaseType }}"
          skip-tag: "true"
      - name: "Release to NPM registry"
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
